dist: xenial
language: python
cache: pip
env:
- TEST_CMD="pytest"
python:
  - "3.6"
before_install:
  - export DJANGO_SETTINGS_MODULE="settings.devel"
install:
  - pip install -r requirements/devel.txt
  - pip install black
before_script:
  - python manage.py migrate
script:
  - $TEST_CMD
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - name: "3.6"
      python: 3.6
    - name: "3.7"
      python: 3.7
    - name: "3.8-dev"
      python: 3.8-dev
    - name: "black"
      python: "3.7"
      env:
      - TEST_CMD="black --check --verbose ."
  allow_failures:
    - name: "3.8-dev"
      python: 3.8-dev
