version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    depends_on:
      - db
    command: prod_web
    ports:
      - "80:8000"
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: npm run build_prod
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
